### ISSUE TITLE
Cannot Override onDestroy(), onPause(), onResume() in MAMActivity

### ISSUE THREAD

**Issue by kchuss** [rzdebskiy/IntuneSDK_XamarinForms_Sample#2]
Hi! I realize this repo is 3 years old at this point, but unfortunately the Intune wrapper still doesn't support Xamarin.Forms Android applications (ahhh why Microsoft, why? It is 2021!). I'm following your wonderful tutorial but when I build, I get these errors:

> error: onDestroy() in XFormsApplicationDroid cannot override onDestroy() in MAMActivity
> 	public void onDestroy ()
>   overridden method is final	
> error: onPause() in XFormsApplicationDroid cannot override onPause() in MAMActivity
> 	public void onPause()
>   overridden method is final	
> error: onResume() in XFormsApplicationDroid cannot override onResume() in MAMActivity
> 	public void onResume ()
>   overridden method is final	

Any ideas? I know it's such a long shot, just banging my head against the wall here. Really appreciate what you've put together.

**Comment by rzdebskiy** [comment]
@kchuss 
Hi Kelly! 
Sorry for delay - as you mentioned this sample is quite old :-) - is this issue still relevant for your work? Or - have you managed to resolve it?
If it is still relevant - please let me know - I can try to repro and we see what happens, as you said it was quite some time since it was actively in use :-)
